### ISSUE TITLE
[DOCUMENTATION] Installation using Pipenv on ArchLinux

### ISSUE THREAD

**Issue by amritagos** [joaomcteixeira/taurenmd#34]
I was able to install taurenmd on using [pipenv](https://github.com/pypa/pipenv). I use ArchLinux:
![archlinux](https://user-images.githubusercontent.com/32496815/80365130-bae7f800-88a4-11ea-8fcb-4b218c371ad6.png)

These are the steps that I followed:
After installing and activating pipenv, I first had to install the dependencies MDAnalysis, MDTraj and OpenMM myself:
`pipenv install mdanalysis mdtraj openmm`
Then I installed taurenmd:
`pipenv install taurenmd`

taurenmd now runs in the pipenv shell:
`pipenv shell`
`taurenmd`
![taurenmd](https://user-images.githubusercontent.com/32496815/80365927-00f18b80-88a6-11ea-9a63-b54f6747082f.png)

**Comment by joaomcteixeira** [comment]
Hi @amritagos 

Thanks for much for your feedback. Just a question, is that `openmm` package the [one from PyPI](https://pypi.org/project/openmm/)?  The `openmm` package from PyPI is just a command-line interface and does not install the core library `simtk` itself. Having said this, `taurenmd` will install but it will fail to read `CIF` files as topologies. Reading topology CIF files is the only functionality for what we use `OpenMM`, and this is a runtime dependency.

Do you have a CIF topology file to try this?

Just an addition, you can install `taurenmd` and all its dependencies from PyPI, that is `MDAnalysis` and `mdtraj` also, using: `pip install taurenmd[all]`.

I will wait for you reply before deciding on updating the documentation.

Thank you, all feedback is very welcomed :smile:

**Comment by amritagos** [comment]
@joaomcteixeira thanks for the prompt response! :)

The `openmm` installed using `Pipenv` is from PYPI, but I have also installed `openmm` directly from the [AUR](https://aur.archlinux.org/packages/openmm/). I think this should probably work for loading a CIF file? 

I have downloaded the data files from the tests folder in the repository for trying out the Usage examples. Would you mind sharing the command for loading the CIF file using taurenmd? I'd be happy to test if this is working. 

Thanks! :)

**Comment by joaomcteixeira** [comment]
Currently, the calculation procedures performed by `taurenmd` use `MDAnalysis`, therefore these do not accept `CIF` format, because `MDAnalysis` does not have `CIF` reader, to my knowledge.

The interfaces that accept `CIF` files are those that use `mdtraj`, where I can integrate with `OpenMM` [here](https://github.com/joaomcteixeira/taurenmd/blob/83b6f74f6cf96bc29e345ebe367c9245d2b563be/src/taurenmd/libs/libmdt.py#L73-L84), which are: `nosol` and `imagemol`. What I do to read `CIF` topology files of large trajectories is to use `nosol` interface to remove the solvent from the trajectory and save also a new topology without the water molecules and in `PDB` format. Then, I use the other `taurenmd` interfaces, such as `trajedit`, or `rmsd`, to analyze the trajectory.

Example data is stored in `tests/data`, but they already have no waters, though you can try:

`taurenmd nosol pcnaA_frame0.cif pcnaA.dcd -o new_top.pdb`

to confirm that you have the `OpenMM` installed and working with `taurenmd`.

Was this explanation helpful?

**Comment by amritagos** [comment]
Thanks, the explanation was very helpful! 
Unfortunately, it seems that the `openmm` from the AUR is also out-of-date and did not work as expected. I am guessing that as long as a working `openmm` version is installed this command will work. I also tried some pre-compiled binaries for `openmm` for Linux, and that didn't work out either (those were older versions too).
However, the `conda` install works fine. It's up to you if you'd like to add ArchLinux to the list of supported OS in the documentation. :)
I will close this issue now, and thanks for the detailed answers.
